### PR TITLE
added entrypoint script and readme file

### PR DESCRIPTION
**Pull request by simakmi**

### CODE REVIEW

**Comment by rodionos** [comment]
I don't think it will build because Dockerfile has to be modified, i.e. copy entrypoint into container, then execute it. To check remove entrypoint from svn repo.

**Comment by simakmi** [comment]
Yes, I forgot to modify Dockerfile. We need to download entrypoint.sh from github:
```
 wget https://raw.githubusercontent.com/axibase/docker-axibase-collector/master/entrypoint.sh -P /opt/axibase-collector/bin/
```

**Comment by rodionos** [comment]
What we're doing in other cases, if for some reason we need to build a custom image, is we do git clone, git update and then docker build. git takes care of efficient downloads (diff) and pull all necessary files. Shall we do the same?

**Comment by simakmi** [comment]
For this case I found safe solution, we can use COPY command inside Dockerfile:

```
COPY entrypoint.sh /tmp/entrypoint.sh
```

then we can move entrypoint.st to the /opt/axibase-collector/bin:

```
mv /tmp/entrypoint.sh /opt/axibase-collector/bin/entrypoint.sh
```

**Comment by simakmi** [comment]
I tested it locally.

**Pull request merged**
